color="Always"
combine_control_expr = false
fn_params_layout = "Vertical"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 20
struct_lit_single_line = false
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true